server:
  port: 9000

service:
  discord-forward-mirai: false
  discord-forward-kook: false
  mirai-forward-channel-names: 更新
  kook-forward-channel-names: 债券

discord:
  enable: false
  token:
  own-guildId: 0

kook:
  enable: false
  token:
  base-url: https://www.kookapp.cn/
  guild-list: /api/v3/guild/list
  channel-list: /api/v3/channel/list
  channel-message: /api/v3/channel/message

mirai:
  enable: false
  admin:
  qq:
  password:
  friends:
  groups:
  device-info-path: device.json
  #  protocol: ANDROID_PHONE ANDROID_PAD ANDROID_WATCH IPAD MACOS
  protocol: MACOS