server:
  port: 9000

service:
  # 条件依赖 {mirai.enabled=true, discord.enabled=true}
  discord-forward: false

mirai:
  enable: true
  admin:
  qq:
  password:
  friends:
  groups:
  device-info-path: device.json
  #  protocol: ANDROID_PHONE ANDROID_PAD ANDROID_WATCH IPAD MACOS
  protocol: ANDROID_WATCH

discord:
  enable: false
  token: