server:
  port: 9000

service:
  discord-forward:
    enable: true
    forward:
      mirai: false
      kook: true


discord:
  enable: false
  token:

mirai:
  enable: false
  admin:
  qq:
  password:
  friends:
  groups:
  device-info-path: device.json
  #  protocol: ANDROID_PHONE ANDROID_PAD ANDROID_WATCH IPAD MACOS
  protocol: MACOS