server:
  port: 9000

service:
  discord-forward-mirai: false
  discord-forward-kook: false
  mirai-forward-channel-names: 更新
  kook-forward-channel-names: 债券,admin测试

discord:
  enable: false
  token:

kook:
  enable: false
  token:
  admin:
  base-url: https://www.kookapp.cn/
  guild-list: /api/v3/guild/list
  guild-view: /api/v3/guild/view
  channel-list: /api/v3/channel/list
  channel-view: /api/v3/channel/view
  channel-message: /api/v3/channel/message
  upload-file: /api/v3/asset/create
  direct-message: /api/v3/direct-message/create

mirai:
  enable: false
  admin:
  qq:
  password:
  friends:
  groups:
  device-info-path: device.json
  #  protocol: ANDROID_PHONE ANDROID_PAD ANDROID_WATCH IPAD MACOS
  protocol: MACOS